### ISSUE TITLE
GUI mode

### ISSUE THREAD

**Issue by nestorac** [linuxdeepin/dde-device-formatter#1]
Hello, I have built and tried dde-device-formatter. I plan to learn from this app how to use your libudisks2-qt5 library. I see that the app has many UI elements, but I cannot execute it in GUI mode, not TUI. AFAIK, I can set '-m' option with some parameter to enable window mode, I guess? What do I have to type? I want to test dde-device-formatterin GUI mode.

Thank you!

**Comment by BLumia** [comment]
Please do read the output from stdout, you need to pass a device path to it. `dde-device-formatter /dev/sda1` for example.

**Comment by nestorac** [comment]
Thank you! It works, I didn't want to format anything, just try the app. :-)
